_reference_jdk: &reference_jdk
  JDK="adopt@1.8"

language: bash
git:
  depth: false
os:
  - osx
  - linux
  - windows
addons:
  apt:
    update: true
    packages:
      - graphviz
  homebrew:
    update: true
    packages:
      - graphviz

env:
  global:
    - GRAVIS_REPO="https://github.com/DanySK/Gravis-CI.git"
    - GRAVIS="$HOME/gravis"
    - TERM=dumb
  matrix:
    - *reference_jdk

stages:
  - check
  - test
  - name: deploy
    if: repo = DanySK/javadoc.io-linker AND type != pull_request

jobs:
  exclude:
    - os: linux
      env: *reference_jdk
      stage: test
  include:
    - name: Base check under Linux
      os: linux
      stage: check
      env: *reference_jdk
    - name: Deployment
      os: linux
      stage: deploy
      env:
        - secure: "S0wlge4ES+SSKJVkHkKvpWkBAdPfbEhjT+yGMtpj4n73ejkCL0wWmm9dGs2LLzMezau4a6uMfJNvueTXey5rWmd7w4xU9dwEjrXt2/HD5tdAd1S8joWD0y7RtcLME5af95vHw1cAir7/+Y8nXdFWi34H5+kvX/LLsIcZtPRhjSlVMpU+bubpKi0smJP3qW4SQzhuU1hkq7cCJsO/LxhoGu3b3aXeyFlWt5PDWDOkRBZywq3fh5kPyKlDvLJnvad1GoYXdNfUEC4ElDz7Df3UNLvRJcUjsaTkHfWgR2bcGGj6nUeZbP4fnekaNfTJVCCzAD7ZUQW+wUvJBsYHRJjYZPBggKBGEOKtds/utYWQ2VfSYelt1oAIO1Mj2koO4rZ0AhvOLyfDD6TxJYgaPMvvFaGPOeGHpJcxnC0cdWGlnf9aKT8Eo7MI9kwkA/cXL840Ecdb0wQS2qPv3A0zApZKOZBV2g1Oy86qvcBdrB5bRXcDA4Qq9iB/87vC1Y4JXtfIE6ZAaejJQKaUjItDvDdg7AM5UwfNztLWrjYHxWajmVDCB7ZHduaKhmkr0n2uVG9AD2bSa9QDpD//wV5YSg1ivYsNO/JsR7ODVAK9fV0SZnsR6HIGMB1iIBdVvz7MpAPC/jAPMUoc+Uf9OGIRioJc2gn3GPbSFKvuBCSF69vJD+8="
        - secure: "JzYascTH/hXiKs3VuhDpe6n8399MjZ/RyjESOULOd2a5DnQKvQunMFU68+w7NDWeKNAzeEt5o5/npW0v0jsQLTJvhwpTHrQ7ZQ5D5H3uh9DncjUnlGPhAnpZ4S08MEG7h85jCyYbdiROpljWq+c6ploDCzVY0wCjsBGKy8elY2+KRWfDyAnJFTqTYACDiZcRLDdbY7821/CUj4YJyZALIRsZMtyOiDNKJlCdkH1v+4viwFmlugDROuOjvUlNP4Hn2417L4wj+1qga+XTe5AjCE5w4cT/wXJHfBR2adc5feM69Jsf9lobY82Vi3cDpx0ASfk/ya8FG6PMwy8VS9r3mg6yLTzbcIS9v7jK6EqN4vX7sQC3puvIGvkrCCN9lJyH4wXKUGpk05J+kFueDsz3nA/wNOaNUJEtbNTIaNr8yXVXZzOVAislTMu+ocA0T40j53YeTT8vO/FZ6HDnMsCQhOKHthiIw07EJpXpR15Nta88raweEVF+CP3xOpAkvWLaG91sgG/dpcl2dkw/uUKmNGYOmsi08sysqeEFZmcezvJnhb3hqpnrxH1F/Oci1HbTDXKG3CAj39LZUicxH6sJDR3aKjL4jMo7fXCWYp/G+czmcFpxDvQdHC9vRPIHIGQCCjz94L93QAKkB+DUBwV+mr5Quz7lPkW5gOlTbJvCm3A="
        - secure: "V3s00dkcKuOWWwsWBs0ea3sUs90kcxtPveCZayFD0QghdMz1WT9MXYIicTjI9wkUdZ6XezoAh5nCIsReMeuz5aPQ3joSs4e6AUrNS/rEeoFYDpfCe8diO1gLdTvB1VfNONFgCyRF8ThbFdt8uBhHVMgAVDwOKMVdK6tz2G4Ew5ALxT2+GV6xukXP5C2A0FSQO6EnQkUS+u0cq+u+P3mm81M+W8Mg/ltvMC0PluJcaDic7Fxo1NJIlpd14cwJb4Fbm7JgeTgHIG0SszWRu+gWOcftfp9vvmX7v707njxCYj52kCb2fPUbUW3AYznon0KEZvjSoJDmGVaj66LGVKgueuPA6e0Z+kGkwblDzC9HOR4RLZFc2iRgr3c3grE9jU7JKZOWRSRdFKtIKcVYOXSx8UpqwizEblv4FKtZaZaL+yqVNqVZF7Q+ySErsb5GwE9Hmcxl/xldrMMY4v4TdZI/MiFmHPPSSq7Uzl2npyqOf5O+zif+1KMUw9HcxmaVU3hPbnlmcxFQA7AjNiNGB/qpml3eVB4FxoWrEJqk7grPbic78dR+bVLwUTZxMEqte0C2zoRHmD08QQE2b0/mp0w1+nWMva9NAcQ05aydW+Om+SsHOfto078TajvmDnLQqEfhz2lnPtg2pvU6WgF1OTSdYAMubXXxAduD7QEfpgi4jc0="
        - *reference_jdk
      install:
        - openssl aes-256-cbc -K $encrypted_62b5a1c46bb0_key -iv $encrypted_62b5a1c46bb0_iv -in prepare_environment.sh.enc -out prepare_environment.sh -d
        - mkdir -p $HOME/.gradle
        - touch $HOME/.gradle/gradle.properties
        - bash prepare_environment.sh
        - rm prepare_environment.sh
      script:
        - travis_retry ./gradlew publishMainPublicationToMavenRepository publishPlugins

before_install:
  - travis_retry git clone --depth 1 $GRAVIS_REPO $GRAVIS
  - source $GRAVIS/install-jdk

script:
  - travis_retry ./gradlew check

before_cache:
  - $GRAVIS/clean-gradle-cache

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
